#include "typedefs.h"
extern GVMT_OBJECT(type) _bytearray;
extern GVMT_OBJECT(type) _module_dict_values;
extern GVMT_OBJECT(type) _binary_pred_api;
extern GVMT_OBJECT(type) _static_method;
extern GVMT_OBJECT(type) _binary_api;
extern GVMT_OBJECT(type) _generator;
extern GVMT_OBJECT(type) _dict;
extern GVMT_OBJECT(type) _partial_operator;
extern GVMT_OBJECT(type) _unary_api;
extern GVMT_OBJECT(type) _bound_method;
extern GVMT_OBJECT(type) _str_buf;
extern GVMT_OBJECT(type) _trace_record;
extern GVMT_OBJECT(type) _Thread;
extern GVMT_OBJECT(type) _Token;
extern GVMT_OBJECT(type) _builtin_function;
extern GVMT_OBJECT(type) _list;
extern GVMT_OBJECT(type) _objint_api;
extern GVMT_OBJECT(type) _tupleiterator;
extern GVMT_OBJECT(type) _comparison_operator;
extern GVMT_OBJECT(type) _set;
extern GVMT_OBJECT(type) _bytes;
extern GVMT_OBJECT(type) _dict_values;
extern GVMT_OBJECT(type) _module;
extern GVMT_OBJECT(type) _info_item0;
extern GVMT_OBJECT(type) _getset_wrapper;
extern GVMT_OBJECT(type) _info_item1;
extern GVMT_OBJECT(type) _type_state;
extern GVMT_OBJECT(type) _listiterator;
extern GVMT_OBJECT(type) _array;
extern GVMT_OBJECT(type) _objintobj_api;
extern GVMT_OBJECT(type) _slice;
extern GVMT_OBJECT(type) _code_object;
extern GVMT_OBJECT(type) _dict_descriptor;
extern GVMT_OBJECT(type) _len_api;
extern GVMT_OBJECT(type) _Constants;
extern GVMT_OBJECT(type) _bytelist;
extern GVMT_OBJECT(type) _Lexer;
extern GVMT_OBJECT(type) _dict_iterator;
extern GVMT_OBJECT(type) _hashtable;
extern GVMT_OBJECT(type) _frozen_type_info;
extern GVMT_OBJECT(type) _class_descriptor;
extern GVMT_OBJECT(type) _range_iterator;
extern GVMT_OBJECT(type) _thread_state;
extern GVMT_OBJECT(type) _class_method;
extern GVMT_OBJECT(type) _range;
extern GVMT_OBJECT(type) _int_slot_descriptor;
extern GVMT_OBJECT(type) _exception_handler;
extern GVMT_OBJECT(type) _float;
extern GVMT_OBJECT(type) _guard;
extern GVMT_OBJECT(type) _scopes;
extern GVMT_OBJECT(type) _operator;
extern GVMT_OBJECT(type) _dict_proxy_iterator;
extern GVMT_OBJECT(type) _info_item2;
extern GVMT_OBJECT(type) _info_item3;
extern GVMT_OBJECT(type) _new_api;
extern GVMT_OBJECT(type) _binary_r_api;
extern GVMT_OBJECT(type) _unary_pred_api;
extern GVMT_OBJECT(type) _NotImplementedType;
extern GVMT_OBJECT(type) _dict_keys;
extern GVMT_OBJECT(type) _BaseException;
extern GVMT_OBJECT(type) _char_array;
extern GVMT_OBJECT(type) _frame;
extern GVMT_OBJECT(type) _Condition;
extern GVMT_OBJECT(type) _function;
extern GVMT_OBJECT(type) _int_vector;
extern GVMT_OBJECT(type) _str_iterator;
extern GVMT_OBJECT(type) _dict_table;
extern GVMT_OBJECT(type) _deferred_state;
extern GVMT_OBJECT(type) _setitem_api;
extern GVMT_OBJECT(type) _type;
extern GVMT_OBJECT(type) _compare_api;
extern GVMT_OBJECT(type) _hash_api;
extern GVMT_OBJECT(type) _method_api;
extern GVMT_OBJECT(type) _deferred;
extern GVMT_OBJECT(type) _str;
extern GVMT_OBJECT(type) _specialiser;
extern GVMT_OBJECT(type) _traceback;
extern GVMT_OBJECT(type) _slot_descriptor;
extern GVMT_OBJECT(type) _file;
extern GVMT_OBJECT(type) _call_descriptor;
extern GVMT_OBJECT(type) _tuple;
extern GVMT_OBJECT(type) _dict_values_iterator;
extern GVMT_OBJECT(type) _complex;
extern GVMT_OBJECT(type) _bool;
extern GVMT_OBJECT(type) _type_info;
extern GVMT_OBJECT(type) _deferred_frame;
extern GVMT_OBJECT(type) _unary_operator;
extern GVMT_OBJECT(type) _binary_operator;
extern GVMT_OBJECT(type) _trace;
extern GVMT_OBJECT(type) _object;
extern GVMT_OBJECT(type) _int_iterator;
extern GVMT_OBJECT(type) _dict_proxy;
extern GVMT_OBJECT(type) _Lock;
extern GVMT_OBJECT(type) _exec_link;
extern GVMT_OBJECT(type) _mono_exec_link;
extern GVMT_OBJECT(type) _poly_exec_link;
extern GVMT_OBJECT(type) _NoneType;

R_type type_bytearray = &_bytearray;
R_type type_module_dict_values = &_module_dict_values;
R_type type_binary_pred_api = &_binary_pred_api;
R_type type_static_method = &_static_method;
R_type type_binary_api = &_binary_api;
R_type type_generator = &_generator;
R_type type_dict = &_dict;
R_type type_partial_operator = &_partial_operator;
R_type type_unary_api = &_unary_api;
R_type type_bound_method = &_bound_method;
R_type type_str_buf = &_str_buf;
R_type type_trace_record = &_trace_record;
R_type type_Thread = &_Thread;
R_type type_Token = &_Token;
R_type type_builtin_function = &_builtin_function;
R_type type_list = &_list;
R_type type_objint_api = &_objint_api;
R_type type_tupleiterator = &_tupleiterator;
R_type type_comparison_operator = &_comparison_operator;
R_type type_set = &_set;
R_type type_bytes = &_bytes;
R_type type_dict_values = &_dict_values;
R_type type_module = &_module;
R_type type_info_item0 = &_info_item0;
R_type type_getset_wrapper = &_getset_wrapper;
R_type type_info_item1 = &_info_item1;
R_type type_type_state = &_type_state;
R_type type_listiterator = &_listiterator;
R_type type_array = &_array;
R_type type_objintobj_api = &_objintobj_api;
R_type type_slice = &_slice;
R_type type_code_object = &_code_object;
R_type type_dict_descriptor = &_dict_descriptor;
R_type type_len_api = &_len_api;
R_type type_Constants = &_Constants;
R_type type_bytelist = &_bytelist;
R_type type_Lexer = &_Lexer;
R_type type_dict_iterator = &_dict_iterator;
R_type type_hashtable = &_hashtable;
R_type type_frozen_type_info = &_frozen_type_info;
R_type type_class_descriptor = &_class_descriptor;
R_type type_range_iterator = &_range_iterator;
R_type type_thread_state = &_thread_state;
R_type type_class_method = &_class_method;
R_type type_range = &_range;
R_type type_int_slot_descriptor = &_int_slot_descriptor;
R_type type_exception_handler = &_exception_handler;
R_type type_float = &_float;
R_type type_guard = &_guard;
R_type type_scopes = &_scopes;
R_type type_operator = &_operator;
R_type type_dict_proxy_iterator = &_dict_proxy_iterator;
R_type type_info_item2 = &_info_item2;
R_type type_info_item3 = &_info_item3;
R_type type_new_api = &_new_api;
R_type type_binary_r_api = &_binary_r_api;
R_type type_unary_pred_api = &_unary_pred_api;
R_type type_NotImplementedType = &_NotImplementedType;
R_type type_dict_keys = &_dict_keys;
R_type type_BaseException = &_BaseException;
R_type type_char_array = &_char_array;
R_type type_frame = &_frame;
R_type type_Condition = &_Condition;
R_type type_function = &_function;
R_type type_int_vector = &_int_vector;
R_type type_str_iterator = &_str_iterator;
R_type type_dict_table = &_dict_table;
R_type type_deferred_state = &_deferred_state;
R_type type_setitem_api = &_setitem_api;
R_type type_type = &_type;
R_type type_compare_api = &_compare_api;
R_type type_hash_api = &_hash_api;
R_type type_method_api = &_method_api;
R_type type_deferred = &_deferred;
R_type type_str = &_str;
R_type type_specialiser = &_specialiser;
R_type type_traceback = &_traceback;
R_type type_slot_descriptor = &_slot_descriptor;
R_type type_file = &_file;
R_type type_call_descriptor = &_call_descriptor;
R_type type_tuple = &_tuple;
R_type type_dict_values_iterator = &_dict_values_iterator;
R_type type_complex = &_complex;
R_type type_bool = &_bool;
R_type type_type_info = &_type_info;
R_type type_deferred_frame = &_deferred_frame;
R_type type_unary_operator = &_unary_operator;
R_type type_binary_operator = &_binary_operator;
R_type type_trace = &_trace;
R_type type_object = &_object;
R_type type_int_iterator = &_int_iterator;
R_type type_dict_proxy = &_dict_proxy;
R_type type_Lock = &_Lock;
R_type type_exec_link = &_exec_link;
R_type type_mono_exec_link = &_mono_exec_link;
R_type type_poly_exec_link = &_poly_exec_link;
R_type type_NoneType = &_NoneType;

