R_AST_alias alias_for_rule_import_as_name(R_str, R_str);
R_AST_expr expr_for_rule_list_expr(R_AST_expr, int line, int column);
R_AST_operator operator_for_rule_PLUSEQUAL(int);
R_AST_operator operator_for_rule_MINUSEQUAL(int);
R_AST_operator operator_for_rule_STAREQUAL(int);
R_AST_operator operator_for_rule_SLASHEQUAL(int);
R_AST_operator operator_for_rule_PERCENTEQUAL(int);
R_AST_operator operator_for_rule_AMPEREQUAL(int);
R_AST_operator operator_for_rule_VBAREQUAL(int);
R_AST_operator operator_for_rule_CIRCUMFLEXEQUAL(int);
R_AST_operator operator_for_rule_LEFTSHIFTEQUAL(int);
R_AST_operator operator_for_rule_RIGHTSHIFTEQUAL(int);
R_AST_operator operator_for_rule_DOUBLESTAREQUAL(int);
R_AST_operator operator_for_rule_DOUBLESLASHEQUAL(int);
R_AST_stmt stmt_for_rule_import_from(R_tuple, R_object, int line, int column);
R_AST_stmt stmt_for_rule_funcdef(R_str, R_AST_arguments, R_AST_expr, R_list, int line, int column);
R_AST_stmt stmt_for_rule_try_stmt(R_list, R_tuple, int line, int column);
R_AST_cmpop cmpop_for_rule_LESS(int);
R_AST_cmpop cmpop_for_rule_GREATER(int);
R_AST_cmpop cmpop_for_rule_EQUAL(int);
R_AST_cmpop cmpop_for_rule_GREATEREQUAL(int);
R_AST_cmpop cmpop_for_rule_LESSEQUAL(int);
R_AST_cmpop cmpop_for_rule_NOTEQUAL(int);
R_AST_cmpop cmpop_for_rule_IN(int);
R_AST_expr expr_for_rule_exprlist(R_list, int, int line, int column);
R_AST_expr expr_for_rule_bracketted_expr(R_AST_expr, int line, int column);
R_AST_expr expr_for_rule_lambdef_nocond(R_AST_arguments, R_AST_expr, int line, int column);
R_AST_expr expr_for_rule_and_expr(R_AST_expr, int, R_AST_expr, int line, int column);
R_AST_expr expr_for_rule_string(R_list, int line, int column);
R_AST_stmt stmt_for_rule_NEWLINE(int, int line, int column);
R_AST_expr expr_for_rule_testlist(R_list, int, int line, int column);
R_AST_stmt stmt_for_rule_classdef(R_str, R_list, R_list, int line, int column);
R_AST_stmt stmt_for_rule_assert_stmt(R_AST_expr, R_AST_expr, int line, int column);
R_AST_stmt stmt_for_rule_for_stmt(R_AST_expr, int, R_AST_expr, R_list, R_list, int line, int column);
R_AST_expr expr_for_rule_lambdef(R_AST_arguments, R_AST_expr, int line, int column);
R_AST_stmt stmt_for_rule_expr_stmt(R_AST_expr, R_object, int line, int column);
R_AST_expr expr_for_rule_decorator(R_list, R_list, int line, int column);
R_AST_expr expr_for_rule_term(R_AST_expr, R_AST_operator, R_AST_expr, int line, int column);
R_AST_operator operator_for_rule_STAR(int);
R_AST_operator operator_for_rule_SLASH(int);
R_AST_operator operator_for_rule_PERCENT(int);
R_AST_operator operator_for_rule_DOUBLESLASH(int);
R_AST_stmt stmt_for_rule_if_stmt(R_AST_expr, R_list, R_list, R_list, int line, int column);
R_int int_for_rule_level(R_list);
R_AST_expr expr_for_rule_or_test(R_list, int line, int column);
R_AST_stmt stmt_for_rule_with_stmt(R_AST_expr, R_AST_expr, R_list, int line, int column);
R_list list_for_rule_comp_for(R_AST_expr, int, R_AST_expr, R_tuple);
R_AST_expr expr_for_rule_expr(R_AST_expr, int, R_AST_expr, int line, int column);
R_tuple convert_dotted_name_to_R_tuple(R_list x);
R_AST_unaryop unaryop_for_rule_PLUS(int);
R_AST_unaryop unaryop_for_rule_MINUS(int);
R_AST_unaryop unaryop_for_rule_TILDE(R_str);
R_AST_expr expr_for_rule_index(R_AST_slice, int line, int column);
R_AST_expr expr_for_rule_comp_if(R_AST_expr, int line, int column);
R_AST_slice slice_for_rule_slice(R_AST_expr, R_AST_slice);
R_AST_stmt stmt_for_rule_nonlocal_stmt(R_list, int line, int column);
R_AST_expr expr_for_rule_shift_expr(R_AST_expr, int, R_AST_expr, int line, int column);
R_AST_expr expr_for_rule_dictorsetmaker(R_AST_expr, R_object, int line, int column);
R_AST_expr expr_for_rule_star_expr(int, R_AST_expr, int line, int column);
R_AST_expr expr_for_rule_power(R_AST_expr, R_tuple, int line, int column);
R_AST_slice slice_for_rule_sliceop(R_AST_expr);
R_AST_expr expr_for_rule_comparison(R_AST_expr, R_list, int line, int column);
R_AST_stmt stmt_for_rule_PASS(int, int line, int column);
R_AST_expr expr_for_rule_arith_expr(R_AST_expr, int, R_AST_expr, int line, int column);
R_AST_expr expr_for_rule_NAME(R_str, int line, int column);
R_AST_expr expr_for_rule_FLOAT(R_str, int line, int column);
R_AST_expr expr_for_rule_INTEGER(R_str, int line, int column);
R_AST_expr expr_for_rule_ELLIPSIS(R_str, int line, int column);
R_AST_expr expr_for_rule_NONE(int, int line, int column);
R_AST_expr expr_for_rule_TRUE(int, int line, int column);
R_AST_expr expr_for_rule_FALSE(int, int line, int column);
R_AST_stmt stmt_for_rule_CONTINUE(int, int line, int column);
R_AST_expr expr_for_rule_unary_expr(R_AST_unaryop, R_AST_expr, int line, int column);
R_AST_expr expr_for_rule_simple(R_AST_expr, R_list, int line, int column);
R_AST_stmt stmt_for_rule_return_stmt(R_AST_expr, int line, int column);
R_AST_expr expr_for_rule_testlist_comp(R_AST_expr, R_list, int line, int column);
R_AST_expr expr_for_rule_xor_expr(R_AST_expr, int, R_AST_expr, int line, int column);
R_AST_mod convert_void_to_R_AST_mod(R_AST_stmt x);
R_AST_mod convert_simple_stmt_to_R_AST_mod(R_list x);
R_AST_mod convert_compound_stmt_to_R_AST_mod(R_AST_stmt x);
R_AST_alias alias_for_rule_dotted_as_name(R_list, R_str);
R_AST_expr expr_for_rule_call(R_list, int line, int column);
R_AST_expr expr_for_rule_not_expr(R_AST_expr, int line, int column);
R_AST_stmt stmt_for_rule_raise_stmt(R_tuple, int line, int column);
R_list list_for_rule_indented_block(int, R_list, int);
R_AST_expr expr_for_rule_attr(R_str, int line, int column);
R_AST_mod mod_for_rule_file_input(R_list);
R_AST_slice slice_for_rule_rslice(R_AST_expr, R_AST_slice);
R_AST_stmt convert_yield_expr_to_R_AST_stmt(R_AST_expr x);
R_AST_cmpop cmpop_for_rule_is(int);
R_object object_for_rule_argument(R_AST_expr, R_object);
R_AST_arguments arguments_for_rule_typedargslist(R_list);
R_AST_stmt stmt_for_rule_BREAK(int, int line, int column);
R_AST_mod mod_for_rule_eval_input(R_AST_expr, R_list);
R_AST_arg arg_for_rule_targ(R_str, R_AST_expr);
R_AST_stmt stmt_for_rule_global_stmt(R_list, int line, int column);
R_AST_stmt stmt_for_rule_import_name(R_list, int line, int column);
R_AST_slice slice_for_rule_subscriptlist(R_list, int);
R_AST_expr expr_for_rule_yield_expr(R_AST_expr, int line, int column);
R_AST_expr expr_for_rule_trinary_expr(R_AST_expr, R_tuple, int line, int column);
R_AST_expr expr_for_rule_and_test(R_list, int line, int column);
R_AST_expr expr_for_rule_dictorset_expr(R_AST_expr, int line, int column);
R_AST_stmt stmt_for_rule_decorated(R_list, R_AST_stmt, int line, int column);
R_AST_cmpop cmpop_for_rule_not_in(int);
R_AST_stmt stmt_for_rule_del_stmt(R_list, int, int line, int column);
R_AST_stmt stmt_for_rule_while_stmt(R_AST_expr, R_list, R_list, int line, int column);
R_AST_arguments arguments_for_rule_varargslist(R_list);

