#ifndef TOKEN_H
#define TOKEN_H
#include "hotpy.h"


#define kind_ERROR 0
#define kind_AMPER 1
#define kind_AMPEREQUAL 2
#define kind_AND 3
#define kind_ARROW 4
#define kind_AS 5
#define kind_ASSERT 6
#define kind_ASSIGN 7
#define kind_AT 8
#define kind_BREAK 9
#define kind_CIRCUMFLEX 10
#define kind_CIRCUMFLEXEQUAL 11
#define kind_CLASS 12
#define kind_COLON 13
#define kind_COMMA 14
#define kind_CONTINUE 15
#define kind_DEDENT 16
#define kind_DEF 17
#define kind_DEL 18
#define kind_DOT 19
#define kind_DOUBLESLASH 20
#define kind_DOUBLESLASHEQUAL 21
#define kind_DOUBLESTAR 22
#define kind_DOUBLESTAREQUAL 23
#define kind_ELIF 24
#define kind_ELLIPSIS 25
#define kind_ELSE 26
#define kind_ENDMARKER 27
#define kind_EQUAL 28
#define kind_EXCEPT 29
#define kind_EXEC 30
#define kind_FALSE 31
#define kind_FINALLY 32
#define kind_FLOAT 33
#define kind_FOR 34
#define kind_FROM 35
#define kind_GLOBAL 36
#define kind_GREATER 37
#define kind_GREATEREQUAL 38
#define kind_IF 39
#define kind_IMPORT 40
#define kind_IN 41
#define kind_INDENT 42
#define kind_INTEGER 43
#define kind_IS 44
#define kind_LAMBDA 45
#define kind_LBRACK 46
#define kind_LCURLY 47
#define kind_LEFTSHIFT 48
#define kind_LEFTSHIFTEQUAL 49
#define kind_LESS 50
#define kind_LESSEQUAL 51
#define kind_LPAREN 52
#define kind_MINUS 53
#define kind_MINUSEQUAL 54
#define kind_NAME 55
#define kind_NEWLINE 56
#define kind_NONE 57
#define kind_NONLOCAL 58
#define kind_NOT 59
#define kind_NOTEQUAL 60
#define kind_OR 61
#define kind_PASS 62
#define kind_PERCENT 63
#define kind_PERCENTEQUAL 64
#define kind_PLUS 65
#define kind_PLUSEQUAL 66
#define kind_RAISE 67
#define kind_RBRACK 68
#define kind_RCURLY 69
#define kind_RETURN 70
#define kind_RIGHTSHIFT 71
#define kind_RIGHTSHIFTEQUAL 72
#define kind_RPAREN 73
#define kind_SEMI 74
#define kind_SLASH 75
#define kind_SLASHEQUAL 76
#define kind_STAR 77
#define kind_STAREQUAL 78
#define kind_STRING 79
#define kind_TILDE 80
#define kind_TRUE 81
#define kind_TRY 82
#define kind_VBAR 83
#define kind_VBAREQUAL 84
#define kind_WHILE 85
#define kind_WITH 86
#define kind_XOR 87
#define kind_YIELD 88

#endif
